apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alurabook-vs
spec:
  hosts:
    - "*"
  gateways:
    - alurabook-gateway
  http:
    - match:
        - uri:
            prefix: /sistema
      rewrite:
        uri: "/"
      route:
        - destination:
            host: sistema-svc
            subset: v1
            port:
              number: 80
      mirror:
        host: sistema-svc
        subset: v2
      mirrorPercentage:
        value: 100.0
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: portal-svc
            port:
              number: 80
