apiVersion: v1
kind: Service
metadata:
  name: portal-svc
  labels:
    app: portal
    service: portal
spec:
  selector:
    app: portal
  ports:
    - port: 80
      targetPort: 80
      name: http
