apiVersion: v1
kind: Service
metadata:
  name: sistema-svc
  labels:
    app: sistema
    service: sistema
spec:
  selector:
    app: sistema
  ports:
    - port: 80
      targetPort: 80
      name: http
